ALTER TABLE LOG_ENTRIES ADD SEVERITY VARCHAR(16);
ALTER TABLE LOG_ENTRIES ADD ERROR_CATEGORY VARCHAR(32);

CREATE INDEX IDX_LOG_ENTRIES_SEVERITY ON LOG_ENTRIES (SEVERITY);
CREATE INDEX IDX_LOG_ENTRIES_CATEGORY ON LOG_ENTRIES (ERROR_CATEGORY);
